// 'use client';
import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/header';
import Footer from '@/components/footer';
import { makeStore, AppStore } from '@/lib/store';
// import { useRef } from 'react';
// import { Provider } from 'react-redux';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const storeRef = useRef<AppStore>();

  // if (!storeRef.current) {
  //   // Create the store instance the first time this renders
  //   storeRef.current = makeStore();
  // }

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        {/* <Provider store={storeRef.current}> */}
        <Header />
        {children}
        <Footer />
        {/* </Provider> */}
      </body>
    </html>
  );
}
