// 'use client';
import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/header';
import Footer from '@/components/footer';
import ReduxProvider from '@/redux/provider';
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Real Estate Business Website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        <ReduxProvider>
          {children}
          <Analytics />
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
